# I need to refer the nodejs tasks in common folder
# catalogue is one role
# common is another role 
# we need to import a task nodejs.yaml into catalogue 


- name: print app version
  debug: 
    msg: "APP  version is  : {{app_version}}"

- name: Install Nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml


- name: install dependencies
  ansible.builtin.command: npm install 
  args:
    chdir:  /app 
# we are doing this part of MongoDB itself
# - name: load schema
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: load-mango-schema

- name: Start Application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup