
- name: checking exists roboshop user
  ansible.builtin.command: id roboshop
  register: out
  ignore_errors: true

#when: out.rc != 0 
- name: create user roboshop
  when: out.rc != 0
  ansible.builtin.user: 
    name: roboshop

- name: checl/ app directory exists or not 
  ansible.builtin.stat:
    path: /app
  register: directory  

- name: print the directory stats
  ansible.builtin.debug:
    msg: "output: {{directory}}"

- name: create directory  /app
  when: directory.stat.exists == False
  ansible.builtin.file:
    path: /app
    state: directory

- name: download {{component}} artifacts
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: extract {{component}} artifact
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app 
    remote_src: yes