 - name: copy mango.repo to yum.repos.d
   ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo 

 - name: Install Mongodb
   ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

 - name: load {{component}} data into mongodb
   ansible.builtin.shell: mongo --host mongodb.joindevops.store < /app/schema/{{component}}.js